# Generated by Django 4.1.3 on 2022-12-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
