# Generated by Django 4.1.3 on 2022-12-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_alter_contact_created_at_alter_contact_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="updated_at",
        ),
    ]
