# Generated by Django 4.1.3 on 2022-11-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="category",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="category",
            field=models.ManyToManyField(to="portfolio.category"),
        ),
    ]
